### ISSUE TITLE
Bug: User Page

### ISSUE THREAD

**Issue by elithrar** [codeu-spring2019/codeu-team35#20]
The navigation for the User Page, and the User Page itself, has a couple of bugs:

* The navigation points to `/your-page` instead of `/user-page.html` - see below

```
➜  git blame src/main/webapp/user-page.html | grep -C 3 'your-page'
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 25)       <nav id="navigation centered">
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 26)         <center>
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 27)           <a href="/">Home</a>
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 28)           <a href="/your-page">Your Page</a>
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 29)           <a href="/map.html">Map</a>
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 30)           <a href="/about.html">About our Team</a>
c38dad95 (Jose Jimenez      2019-03-17 23:33:08 -0700 31)              </center>
```

* The `buildUI` function is no longer available in the window namespace and thus the UI/text editor fails to load - e.g. http://localhost:8080/user-page.html?user=test@example.com

```
Uncaught ReferenceError: buildUI is not defined
    at onload (user-page.html?user=test@example.com:23)
```

Actions:

* Fix URL in navigation - to reflect previous `/user-page.html` path by updating `index.html`
* Debug & resolve user page customization bug - e.g. consider going back to an earlier commit via `git checkout $COMMIT_NUMBER` and figuring out the problem via `git diff master..$COMMIT_NUMBER` to see what changed.

cc/ @gcheng21

**Comment by josejimenezolivas** [comment]
Hi I actually had the same error when I pulled from master I submitted a pull request 7 days ago under AboutMe

The reason was for a <script> tag deletion for the user-page-loader.js source.
